version: '3.3' # docker version
# volumes:
#   postgres-data:

services:
  www:
    image: php:7.4.9-apache
    build: .
    volumes:
      - ./:/var/www/html # sync project dir with container web dir
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    ports: 
      - 8000:80
      - 443:443
  db: 
    image: postgres:latest
    env_file:
      - .env.docker
    volumes:
      # - postgres-data:/var/lib/postgresql/data
      - ./migrate/stopify.sql:/docker-entrypoint-initdb.d/dumpfile.sql
    ports:
        - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080